# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

MAKEOPTS="-j6 -l8"

# Appending getbinpkg to the list of values within the FEATURES variable
EMERGE_DEFAULT_OPTS="${EMERGE_DEFAULT_OPTS} --binpkg-respect-use=y"
FEATURES="${FEATURES} binpkg-request-signature"
ACCEPT_LICENSE="-* @FREE @BINARY-REDISTRIBUTABLE"

USE="dist-kernel networkmanager"

GRUB_PLATFORMS="efi-64"

GENTOO_MIRRORS="http://gentoo-mirror.flux.utah.edu/ \
    https://us.mirrors.cicku.me/gentoo/ \
    http://www.gtlib.gatech.edu/pub/gentoo"
